### ISSUE TITLE
Insecure auth key using rand()

### ISSUE THREAD

**Issue by ghost** [Times-0/Register-cp#1]
Related to this line:

https://github.com/Times-0/Register-cp/blob/a6948511520d27748f9517b0423694f53e169939/create/ajax/index.php#L231

It has been known that using rand() is insecure. In order to add a bit more randomness, the following should be used:

```php
md5(openssl_random_pseudo_bytes(16));
```

This will create an output like so: `7dc7f61022b2a88df34c1e476ea078ff`

MD5 is not really necessary. To avoid collision even more, an authorization key should be removed completely after a user is authorized, resulting in the authorization key getting recycled. Unauthorized keys should be removed after 7 days of not being authorized.

**Comment by valid22** [comment]
Ref: https://github.com/Times-0/Register-cp/commit/6da54498a4d6da9fc427fc484b514c726811dd1c
There you go.

> To avoid collision even more, an authorization key should be removed completely after a user is authorized, resulting in the authorization key getting recycled

I'm not sure why you quoted it, but afaik key is removed once activated.

> Unauthorized keys should be removed after 7 days of not being authorized.

Um, well, that's not part of the register, depends upon the server.
